AWSTemplateFormatVersion: '2010-09-09'
Description: Master stack for LDC-AUTH infrastructure using nested stacks

Parameters:
  InstanceType:
    Description: WebServer EC2 instance type (has default, AllowedValues)
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
    ConstraintDescription: must be a valid EC2 instance type.

  NetworkUser:
    Description: Network username
    Type: String
    Default: NTABORD

  TemplateURL:
    Description: URL of the nested stack template
    Type: String
    Default: https://ntabord-s3.s3.us-east-1.amazonaws.com/sg-template.yaml

  MaxInstances:
    Type: Number
    Description: Maximum number of EC2 instances in the PDN ASG
    Default: 2
    MinValue: 1
    MaxValue: 3

  PrivateSubnetApdn:
    Description: Subnet ID
    Type: AWS::EC2::Subnet::Id
  
  PrivateSubnetBdev:
    Description: Subnet ID
    Type: AWS::EC2::Subnet::Id
  
  MyVPC:
    Description: VPC to operate in
    Type: AWS::EC2::VPC::Id

  MyInternetGateway:
    Description: ID de un Internet Gateway existente (ya adjunto a la VPC)
    Type: String

Resources:
  ServerSecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Ref TemplateURL
      Parameters:
        VPCId: !Ref MyVPC
        NetworkUsername: !Ref NetworkUser
      TimeoutInMinutes: 5

  MyPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MyPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  MySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetApdn
      RouteTableId: !Ref MyPublicRouteTable

  MySubnetRouteTableAssociationDev:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetBdev
      RouteTableId: !Ref MyPublicRouteTable

  MyALBPDN:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub LDC-AUTH-ALB-${NetworkUser}-PDN
      Subnets:
        - !Ref PrivateSubnetBdev
        - !Ref PrivateSubnetApdn
      SecurityGroups: 
        - !GetAtt ServerSecurityGroupStack.Outputs.EC2GroupIdPDN
      Scheme: internet-facing
      Type: application

  MyALBDEV:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub LDC-AUTH-ALB-${NetworkUser}-DEV
      Subnets:
        - !Ref PrivateSubnetBdev
        - !Ref PrivateSubnetApdn
      SecurityGroups: 
        - !GetAtt ServerSecurityGroupStack.Outputs.EC2GroupIdDEV
      Scheme: internet-facing
      Type: application

  TargetGroupPDN:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref MyVPC
      Port: 4200
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /
      Matcher:
        HttpCode: 200

  TargetGroupDEV:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref MyVPC
      Port: 4200
      Protocol: HTTP
      TargetType: instance
      Targets:
        - Id: !Ref MyEC2Instance
      HealthCheckPath: /
      Matcher:
        HttpCode: 200

  ALBListenerDEV:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyALBDEV
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: 
            Ref: TargetGroupDEV
            
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyALBPDN
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: 
            Ref: TargetGroupPDN

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub "AUTH-EC2-${NetworkUser}-PDN"
        ImageId: ami-0a7d80731ae1b2435
        NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: 
            Ref: PrivateSubnetApdn
          Groups:
            - !GetAtt ServerSecurityGroupStack.Outputs.EC2GroupIdDEV
        BlockDeviceMappings:
          - DeviceName: "/dev/sda1"
            Ebs:
              VolumeType: "gp2"
              VolumeSize: "20"
        UserData:
          Fn::Base64: |
            #!/bin/bash -xe
            exec > /var/log/user-data.log 2>&1
            echo "=== INICIANDO SCRIPT DE USUARIO ==="
            apt-get update -y
            apt-get upgrade -y
            curl -fsSL https://get.docker.com/ -o get-docker.sh
            sh get-docker.sh
            usermod -aG docker ubuntu
            docker --version || echo "Docker no se instaló correctamente"
            git clone https://github.com/nastab/cloudformation-challenge.git
            cd cloudformation-challenge/
            PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
            API_URL=http://$PUBLIC_IP:8080/api docker compose up -d
            echo "=== FIN DEL SCRIPT DE USUARIO ==="


  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub LDC-AUTH-ASG-${NetworkUser}-PDN
      VPCZoneIdentifier: 
        - !Ref PrivateSubnetApdn
      MinSize: "1"
      MaxSize: !Ref MaxInstances
      DesiredCapacity: !Ref MaxInstances
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - !Ref TargetGroupPDN
      Tags:
        - Key: Name
          Value: !Sub LDC-AUTH-ASG-EC2-${NetworkUser}-PDN
          PropagateAtLaunch: true

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0a7d80731ae1b2435
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: "20"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet: 
            - !GetAtt ServerSecurityGroupStack.Outputs.EC2GroupIdDEV
          SubnetId: 
            Ref: PrivateSubnetBdev
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
            exec > /var/log/user-data.log 2>&1
            echo "=== INICIANDO SCRIPT DE USUARIO ==="
            apt-get update -y
            apt-get upgrade -y
            curl -fsSL https://get.docker.com/ -o get-docker.sh
            sh get-docker.sh
            usermod -aG docker ubuntu
            docker --version || echo "Docker no se instaló correctamente"
            git clone https://github.com/nastab/cloudformation-challenge.git
            cd cloudformation-challenge/
            PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
            API_URL=http://$PUBLIC_IP:8080/api docker compose up -d
            echo "=== FIN DEL SCRIPT DE USUARIO ==="    
      Tags:
        - Key: Name
          Value: !Sub "AUTH-EC2-${NetworkUser}-DEV"

Outputs:
  NetworkUserName:
    Value: !Ref NetworkUser
    Description: The user-defined network name

  SecurityGroupDEV:
    Value: !GetAtt ServerSecurityGroupStack.Outputs.EC2GroupIdDEV

  SecurityGroupPDN:
    Value: !GetAtt ServerSecurityGroupStack.Outputs.EC2GroupIdPDN

  SecurityGroupNameDEV:
    Value: !Sub LDC-AUTH-SG-${NetworkUser}-DEV
  
  SecurityGroupNamePDN:
    Value: !Sub LDC-AUTH-SG-${NetworkUser}-PDN

  LoadBalancerDEV:
    Value: !Sub LDC-AUTH-ALB-${NetworkUser}-DEV

  LoadBalancerPDN:
    Value: !Sub "LDC-AUTH-ALB-${NetworkUser}-PDN"

  EC2NameDEV:
    Value: !Sub LDC-AUTH-EC2-${NetworkUser}-DEV

  EC2NamePDN:
    Value: !Sub LDC-AUTH-EC2-${NetworkUser}-PDN
