Parameters:
  InstanceType:
    Description: WebServer EC2 instance type (has default, AllowedValues)
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
    ConstraintDescription: must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  MyVPC:
    Description: VPC to operate in
    Type: AWS::EC2::VPC::Id

  NetworkUsername:
    Description: Network username
    Type: String
    Default: NTABORD

  env:
    Description: Environment
    Type: String
    AllowedValues: [DEV, PDN]

  TemplateURL:
    Description: URL of the nested stack template
    Type: String
    Default: https://cf-templates-ixehohauydzv-us-east-1.s3.us-east-1.amazonaws.com/sg-template.yaml

  MyInternetGateway:
    Description: ID de un Internet Gateway existente (ya adjunto a la VPC)
    Type: String

  MySubnetID:
    Description: Subnet ID
    Type: AWS::EC2::Subnet::Id

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>

Conditions:
  IsPDN: !Equals [!Ref env, "PDN"]
  IsDEV: !Equals [!Ref env, "DEV"]

Resources:

  ServerSecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateURL
      Parameters:
        ApplicationName: !Ref AWS::StackName
        VPCId: !Ref MyVPC
      TimeoutInMinutes: 5

  MyPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MyPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  MySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MySubnetID
      RouteTableId: !Ref MyPublicRouteTable

  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "LDC-AUTH-ALB-${NetworkUsername}-${env}"
      Subnets: !Ref Subnets
      SecurityGroups: 
        - !GetAtt ServerSecurityGroupStack.Outputs.SSHGroupId
      Scheme: internet-facing
      Type: application

  TargetGroupPDN:
    Condition: IsPDN
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref MyVPC
      Port: 4200
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /
      Matcher:
        HttpCode: 200

  TargetGroupDEV:
    Condition: IsDEV
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref MyVPC
      Port: 4200
      Protocol: HTTP
      TargetType: instance
      Targets:
        - Id: !Ref MyEC2Instance
      HealthCheckPath: /
      Matcher:
        HttpCode: 200

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyALB
      Port: 4200
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !If
            - IsPDN
            - !Ref TargetGroupPDN
            - !Ref TargetGroupDEV

  LaunchTemplate:
    Condition: IsPDN
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub "AUTH-EC2-${NetworkUsername}-${env}"
        ImageId: ami-0a7d80731ae1b2435
        NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: 
            Ref: MySubnetID
          Groups:
            - !GetAtt ServerSecurityGroupStack.Outputs.SSHGroupId
        KeyName: !Ref KeyName
        BlockDeviceMappings:
          - DeviceName: "/dev/sda1"
            Ebs:
              VolumeType: "gp2"
              VolumeSize: "20"
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            exec > /var/log/user-data.log 2>&1
            echo "=== INICIANDO SCRIPT DE USUARIO ==="
            apt-get update -y
            apt-get upgrade -y
            curl -fsSL https://get.docker.com/ -o get-docker.sh
            sh get-docker.sh
            usermod -aG docker ubuntu
            docker --version || echo "Docker no se instaló correctamente"
            git clone https://github.com/nastab/cloudformation-challenge.git
            cd cloudformation-challenge/
            PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
            API_URL=http://$PUBLIC_IP:8080/api docker compose up -d
            echo "=== FIN DEL SCRIPT DE USUARIO ==="


  AutoScalingGroup:
    Condition: IsPDN
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref Subnets
      MinSize: "1"
      MaxSize: "2"
      DesiredCapacity: "1"
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - !Ref TargetGroupPDN      

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Condition: IsDEV
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0a7d80731ae1b2435
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeType: "gp2"
            VolumeSize: "20"
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet: 
            - !GetAtt ServerSecurityGroupStack.Outputs.SSHGroupId
          SubnetId: 
            Ref: MySubnetID
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
            exec > /var/log/user-data.log 2>&1
            echo "=== INICIANDO SCRIPT DE USUARIO ==="
            apt-get update -y
            apt-get upgrade -y
            curl -fsSL https://get.docker.com/ -o get-docker.sh
            sh get-docker.sh
            usermod -aG docker ubuntu
            docker --version || echo "Docker no se instaló correctamente"
            git clone https://github.com/nastab/cloudformation-challenge.git
            cd cloudformation-challenge/
            PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
            API_URL=http://$PUBLIC_IP:8080/api docker compose up -d
            echo "=== FIN DEL SCRIPT DE USUARIO ==="    
      Tags:
        - Key: Name
          Value: !Sub "AUTH-EC2-${NetworkUsername}-${env}"
